# Auto-generated by Terraform — do not edit by hand.

[master]
${master_name} ansible_host=${master_public_ip} k8s_node_ip=${master_private_ip} master_public_ip=${master_public_ip}

[workers]
%{ for i, name in worker_names ~}
${name} ansible_host=${worker_public_ips[i]} k8s_node_ip=${worker_private_ips[i]}
%{ endfor ~}

[k8s:children]
master
workers

[all:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=~/ssh_key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
letsencrypt_email=${letsencrypt_email}
use_staging_issuer=${use_staging_issuer}
