# Auto-generated by Terraform — do not edit by hand.
# Re-rendered every time master/worker IPs change.

[master]
${master_name} ansible_host=${master_public_ip} private_ip=${master_private_ip}

[workers]
%{ for i, name in worker_names ~}
${name} ansible_host=${worker_public_ips[i]} private_ip=${worker_private_ips[i]}
%{ endfor ~}

[k8s_cluster:children]
master
workers

[all:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=${ssh_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
kubernetes_version=${kubernetes_version}
k8s_minor_version=${k8s_minor_version}
calico_version=${calico_version}
ingress_nginx_version=${ingress_nginx_version}
