output "lb_public_ip" {
  value       = module.lb.public_ip_address
  description = "Load Balancer public IP — point DuckDNS at this for HA"
}

output "master_public_ip" {
  value       = module.public_ip.ip_addresses[0]
  description = "Master VM's individual public IP (for SSH; not for app traffic)"
}

output "worker_public_ips" {
  value       = slice(module.public_ip.ip_addresses, 1, length(local.node_name))
  description = "Public IPs of the workers"
}

output "ssh_command_master" {
  value       = "ssh -i ~/ssh_key.pem ${var.username}@${module.public_ip.ip_addresses[0]}"
  description = "Copy-paste SSH command for the master"
}

output "verify_cluster_command" {
  value       = "ssh -i ~/ssh_key.pem ${var.username}@${module.public_ip.ip_addresses[0]} 'kubectl get nodes -o wide'"
  description = "Run kubectl get nodes against the new cluster"
}

output "summary" {
  value = <<-EOT

  ╔════════════════════════════════════════════════════════════════╗
  ║              PHASE 1 DEPLOYMENT COMPLETE                       ║
  ╚════════════════════════════════════════════════════════════════╝

   Master IP:     ${module.public_ip.ip_addresses[0]}
   SSH key:       ~/ssh_key.pem (auto-generated by Terraform)
   SSH command:   ssh -i ~/ssh_key.pem ${var.username}@${module.public_ip.ip_addresses[0]}

  ── VERIFY ────────────────────────────────────────────────────────
   ssh -i ~/ssh_key.pem ${var.username}@${module.public_ip.ip_addresses[0]}
   kubectl get nodes -o wide
   kubectl get pods -A

  ── NEXT ──────────────────────────────────────────────────────────
   Phase 2: configure DuckDNS to point at ${module.public_ip.ip_addresses[0]}
   Phase 3: helm install jenkins ...

  ══════════════════════════════════════════════════════════════════
  EOT
}
