output "master_public_ip" {
  value       = azurerm_public_ip.k8s[0].ip_address
  description = "Public IP of the master"
}

output "worker_public_ips" {
  value       = slice(azurerm_public_ip.k8s[*].ip_address, 1, length(local.node_name))
  description = "Public IPs of the workers"
}

output "ssh_command_master" {
  value       = "ssh -i ~/ssh_key.pem ${var.username}@${azurerm_public_ip.k8s[0].ip_address}"
  description = "Copy-paste SSH command for the master"
}

output "verify_cluster_command" {
  value       = "ssh -i ~/ssh_key.pem ${var.username}@${azurerm_public_ip.k8s[0].ip_address} 'kubectl get nodes -o wide'"
  description = "Run kubectl get nodes against the new cluster"
}

output "summary" {
  value = <<-EOT

  ╔════════════════════════════════════════════════════════════════╗
  ║              PHASE 1 DEPLOYMENT COMPLETE                       ║
  ╚════════════════════════════════════════════════════════════════╝

   Master IP:     ${azurerm_public_ip.k8s[0].ip_address}
   SSH key:       ~/ssh_key.pem (auto-generated by Terraform)
   SSH command:   ssh -i ~/ssh_key.pem ${var.username}@${azurerm_public_ip.k8s[0].ip_address}

  ── VERIFY ────────────────────────────────────────────────────────
   ssh -i ~/ssh_key.pem ${var.username}@${azurerm_public_ip.k8s[0].ip_address}
   kubectl get nodes -o wide
   kubectl get pods -A

  ── NEXT ──────────────────────────────────────────────────────────
   Phase 2: configure DuckDNS to point at ${azurerm_public_ip.k8s[0].ip_address}
   Phase 3: helm install jenkins ...

  ══════════════════════════════════════════════════════════════════
  EOT
}
